<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Rafael Santamaría Heredia y [Nombres de tu equipo]">

<title>Análisis Probabilístico del Transporte en México mediante Redes Bayesianas</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="ARTICULO1_RBM_files/libs/clipboard/clipboard.min.js"></script>
<script src="ARTICULO1_RBM_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="ARTICULO1_RBM_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="ARTICULO1_RBM_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="ARTICULO1_RBM_files/libs/quarto-html/popper.min.js"></script>
<script src="ARTICULO1_RBM_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="ARTICULO1_RBM_files/libs/quarto-html/anchor.min.js"></script>
<link href="ARTICULO1_RBM_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="ARTICULO1_RBM_files/libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="ARTICULO1_RBM_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="ARTICULO1_RBM_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="ARTICULO1_RBM_files/libs/bootstrap/bootstrap-9e3ffae467580fdb927a41352e75a2e0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css">

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#abstract" id="toc-abstract" class="nav-link active" data-scroll-target="#abstract">Abstract</a></li>
  <li><a href="#introducción" id="toc-introducción" class="nav-link" data-scroll-target="#introducción">1. Introducción</a>
  <ul class="collapse">
  <li><a href="#contexto-de-la-movilidad-en-méxico" id="toc-contexto-de-la-movilidad-en-méxico" class="nav-link" data-scroll-target="#contexto-de-la-movilidad-en-méxico">1.1 Contexto de la Movilidad en México</a></li>
  <li><a href="#modelado-probabilístico-mediante-redes-bayesianas" id="toc-modelado-probabilístico-mediante-redes-bayesianas" class="nav-link" data-scroll-target="#modelado-probabilístico-mediante-redes-bayesianas">1.2 Modelado Probabilístico mediante Redes Bayesianas</a></li>
  <li><a href="#objetivos-e-hipótesis-de-investigación-queries" id="toc-objetivos-e-hipótesis-de-investigación-queries" class="nav-link" data-scroll-target="#objetivos-e-hipótesis-de-investigación-queries">1.3 Objetivos e Hipótesis de Investigación (Queries)</a></li>
  </ul></li>
  <li><a href="#metodología" id="toc-metodología" class="nav-link" data-scroll-target="#metodología">2. Metodología</a>
  <ul class="collapse">
  <li><a href="#procesamiento-de-datos-y-construcción-de-variables" id="toc-procesamiento-de-datos-y-construcción-de-variables" class="nav-link" data-scroll-target="#procesamiento-de-datos-y-construcción-de-variables">2.1 Procesamiento de Datos y Construcción de Variables</a></li>
  <li><a href="#modelado-estructural-dags" id="toc-modelado-estructural-dags" class="nav-link" data-scroll-target="#modelado-estructural-dags">2.2 Modelado Estructural (DAGs)</a></li>
  <li><a href="#inferencia-bayesiana" id="toc-inferencia-bayesiana" class="nav-link" data-scroll-target="#inferencia-bayesiana">2.3 Inferencia Bayesiana</a></li>
  </ul></li>
  <li><a href="#aplicación-y-resultados" id="toc-aplicación-y-resultados" class="nav-link" data-scroll-target="#aplicación-y-resultados">3. Aplicación y Resultados</a>
  <ul class="collapse">
  <li><a href="#evaluación-y-comparación-de-estructuras-score-bic" id="toc-evaluación-y-comparación-de-estructuras-score-bic" class="nav-link" data-scroll-target="#evaluación-y-comparación-de-estructuras-score-bic">3.1 Evaluación y Comparación de Estructuras (Score BIC)</a></li>
  <li><a href="#inferencia-probabilística-y-respuesta-a-las-queries-asignadas" id="toc-inferencia-probabilística-y-respuesta-a-las-queries-asignadas" class="nav-link" data-scroll-target="#inferencia-probabilística-y-respuesta-a-las-queries-asignadas">3.2 Inferencia Probabilística y Respuesta a las Queries Asignadas</a></li>
  </ul></li>
  <li><a href="#conclusiones" id="toc-conclusiones" class="nav-link" data-scroll-target="#conclusiones">4. Conclusiones</a></li>
  <li><a href="#referencias" id="toc-referencias" class="nav-link" data-scroll-target="#referencias">5. Referencias</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Análisis Probabilístico del Transporte en México mediante Redes Bayesianas</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Rafael Santamaría Heredia y [Nombres de tu equipo] </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="abstract" class="level2">
<h2 class="anchored" data-anchor-id="abstract">Abstract</h2>
<p>Este estudio analiza los patrones de movilidad urbana, hábitos de transporte y percepción de seguridad en México a partir de los microdatos de la Encuesta Nacional de Movilidad y Transporte (ENMT). Mediante el paradigma de Redes Bayesianas Multinomiales, se evaluaron tres estructuras probabilísticas teóricas (Socioeconómica, Infraestructura y Riesgo) y se contrastaron con una estructura latente descubierta algorítmicamente mediante el algoritmo <em>Hill-Climbing</em>. Los modelos fueron evaluados cuantitativamente a través del Criterio de Información Bayesiano (BIC), resultando la topología aprendida por <em>Hill-Climbing</em> como la de mejor ajuste empírico (<span class="math inline">\text{BIC} = -8653.48</span>). Utilizando la red óptima y estimación bayesiana con suavizado de Dirichlet (<span class="math inline">\text{iss} = 10</span>), se resolvieron cuatro interrogantes probabilísticas clave (queries) empleando técnicas de simulación de Monte Carlo (<em>Likelihood Weighting</em> y <em>Logic Sampling</em>). Los hallazgos revelan que: (1) el uso de tractor agrícola es <span class="math inline">4.08</span> veces más probable en localidades rurales de menos de 15,000 habitantes (<span class="math inline">3.55\%</span> vs <span class="math inline">0.87\%</span>); (2) las mujeres conductoras presentan una mayor probabilidad condicionada de uso frecuente del claxon (<span class="math inline">35.47\%</span>) en comparación con los hombres (<span class="math inline">27.58\%</span>); (3) la tenencia de automóvil no presenta una diferencia estadísticamente significativa en la incidencia delictiva sufrible (<span class="math inline">G^2 = 2.2965, p = 0.1297</span>); y (4) el nivel socioeconómico y la duración del viaje determinan fuertemente la elección del transporte público (<span class="math inline">61.35\%</span> para estratos de ingresos bajos en trayectos largos).</p>
</section>
<section id="introducción" class="level2">
<h2 class="anchored" data-anchor-id="introducción">1. Introducción</h2>
<section id="contexto-de-la-movilidad-en-méxico" class="level3">
<h3 class="anchored" data-anchor-id="contexto-de-la-movilidad-en-méxico">1.1 Contexto de la Movilidad en México</h3>
<p>La movilidad urbana y rural en México constituye un fenómeno socioespacial complejo, caracterizado por marcadas disparidades en la disponibilidad de infraestructura, tiempos de traslado, seguridad vial y exposición a patrones de victimización. En las últimas décadas, el acelerado e ineficiente crecimiento urbano, sumado a la brecha socioeconómica entre regiones, ha consolidado un sistema de transporte altamente heterogéneo. Mientras que los grandes centros urbanos concentran redes masivas de transporte público saturadas y un incremento sostenido de la flota vehicular particular, las localidades de menor densidad poblacional dependen de modos no motorizados, transporte informal o vehículos de uso agrícola adaptados a labores de traslado rutinario.</p>
<p>Formular e implementar políticas públicas efectivas en materia de ordenamiento territorial, infraestructura y seguridad vial requiere superar los enfoques descriptivos tradicionales que analizan variables de manera aislada. La toma de decisiones en el ámbito público exige herramientas cuantitativas capaces de modelar la interacción simultánea entre factores sociodemográficos, hábitos de viaje, tenencia de activos y percepciones del entorno.</p>
</section>
<section id="modelado-probabilístico-mediante-redes-bayesianas" class="level3">
<h3 class="anchored" data-anchor-id="modelado-probabilístico-mediante-redes-bayesianas">1.2 Modelado Probabilístico mediante Redes Bayesianas</h3>
<p>En este contexto, las <strong>Redes Bayesianas Multinomiales (RBM)</strong> emergen como una alternativa analítica robusta frente a los modelos econométricos convencionales. Al estructurar las relaciones entre variables categóricas mediante un Grafo Acíclico Dirigido (DAG, por sus siglas en inglés), las RBMs permiten:</p>
<ol type="1">
<li><strong>Capturar dependencias no lineales y complejas:</strong> Representan interacciones multivariadas sin asumir normalidad en la distribución de los datos.</li>
<li><strong>Propagar incertidumbre e inferir bajo evidencia parcial:</strong> Permiten calcular probabilidades condicionales exactas o aproximadas ante la presencia de escenarios hipotéticos o datos faltantes.</li>
<li><strong>Evaluar hipótesis causales y estructurales:</strong> Facilitan la comparación objetiva entre marcos teóricos competitivos y algoritmos de aprendizaje de datos mediante métricas formales de bondad de ajuste, tales como el Criterio de Información Bayesiano (BIC).</li>
</ol>
<p>Aprovechando los microdatos empíricos de la <strong>Encuesta Nacional de Movilidad y Transporte (ENMT)</strong> desarrollada por el Instituto de Investigaciones Jurídicas de la UNAM, este trabajo aplica modelos de redes bayesianas para desentrañar las relaciones latentes que gobiernan el comportamiento de movilidad en la población mexicana.</p>
</section>
<section id="objetivos-e-hipótesis-de-investigación-queries" class="level3">
<h3 class="anchored" data-anchor-id="objetivos-e-hipótesis-de-investigación-queries">1.3 Objetivos e Hipótesis de Investigación (Queries)</h3>
<p>El objetivo principal de este artículo es evaluar la pertinencia de distintos grafos teóricos y estructurales aprendidos por datos para resolver cuatro interrogantes fundamentales sobre el sistema de transporte nacional. Estas preguntas se traducen formalmente en las siguientes hipótesis probabilísticas condicionales:</p>
<ul>
<li><strong>Hipótesis 1 (Uso de transporte agrícola por entorno geográfico):</strong>
<ul>
<li><em>Query 1:</em> ¿La probabilidad de utilizar el tractor como medio de transporte cotidiano u ocasional es significativamente mayor en localidades rurales o de baja densidad poblacional (<span class="math inline">&lt;15,000</span> habitantes) en comparación con entornos urbanos? Se evalúa la dependencia entre el tamaño de localidad y el uso de vehículos no convencionales.</li>
</ul></li>
<li><strong>Hipótesis 2 (Comportamiento de conducción y diferencias de género):</strong>
<ul>
<li><em>Query 2:</em> Condicionado a la tenencia de automóvil propio en el hogar, ¿los hombres presentan una probabilidad mayor de incurrir en el uso excesivo del claxon en comparación con las mujeres? Se analiza la interacción entre género, propiedad vehicular y hábitos de conducción en el espacio vial.</li>
</ul></li>
<li><strong>Hipótesis 3 (Tenencia vehicular y victimización delictiva):</strong>
<ul>
<li><em>Query 3:</em> ¿Existe una diferencia estadísticamente significativa en la incidencia de delitos en el transporte entre las personas que disponen de vehículo particular y aquellas que dependen de otros medios? Se contrasta la exposición al riesgo delictivo en función del acceso al auto privado.</li>
</ul></li>
<li><strong>Hipótesis 4 (Elección modal, estrato socioeconómico y tiempo de trayecto):</strong>
<ul>
<li><em>Query 4:</em> ¿El nivel de ingreso familiar y la duración del viaje determinan conjuntamente la probabilidad de optar por el transporte público masivo en lugar del auto particular? Se examina la sensibilidad modal ante restricciones económicas y de tiempo de traslado.</li>
</ul></li>
</ul>
</section>
</section>
<section id="metodología" class="level2">
<h2 class="anchored" data-anchor-id="metodología">2. Metodología</h2>
<section id="procesamiento-de-datos-y-construcción-de-variables" class="level3">
<h3 class="anchored" data-anchor-id="procesamiento-de-datos-y-construcción-de-variables">2.1 Procesamiento de Datos y Construcción de Variables</h3>
<p>El análisis se fundamentó en los microdatos de la Encuesta Nacional de Movilidad y Transporte (ENMT). El preprocesamiento se enfocó en el tratamiento de valores nulos (NS/NC) y la recodificación de categorías estructurales para evitar la pérdida de información sistémica. Un caso crítico fue la variable sobre el uso excesivo del claxon (<code>p15_3</code>), donde el código original asignado a quienes no poseen automóvil se trató como una categoría estructural válida (“No aplica”) en lugar de un valor faltante. Esto previno la eliminación del 76% de la muestra durante los procesos de filtradO.</p>
<p>Para responder a las interrogantes de investigación, se construyeron variables derivadas que consolidaron las dimensiones del instrumento original:</p>
<ul>
<li><strong>Medio Principal:</strong> Se sintetizaron 22 preguntas independientes sobre modos de transporte (<code>p1a_1</code> a <code>p1a_22</code>) en una única variable categórica (Automóvil particular, Público masivo, Taxi/Plataforma, No motorizado, Otro), priorizando estadísticamente los medios reportados como de uso cotidiano.</li>
<li><strong>Incidencia Delictiva:</strong> Se generó una variable binaria (<code>victima_delito</code>) mediante la agregación lógica (OR) de siete modalidades de victimización en el transporte reportadas individualmente (<code>p25_1_1</code> a <code>p25_1_7</code>).</li>
<li><strong>Tiempo de Viaje:</strong> La variable continua de duración del trayecto principal (<code>dura1</code>) se discretizó en tres intervalos ordenados: corto (<span class="math inline">\leq</span> 20 min), medio (21-40 min) y largo (<span class="math inline">&gt;</span> 40 min).</li>
</ul>
</section>
<section id="modelado-estructural-dags" class="level3">
<h3 class="anchored" data-anchor-id="modelado-estructural-dags">2.2 Modelado Estructural (DAGs)</h3>
<p>Para modelar las relaciones de dependencia probabilística, se propusieron inicialmente tres Grafos Acíclicos Dirigidos (DAGs) basados en hipótesis teóricas deductivas:</p>
<ul>
<li><strong>DAG 1 (Socioeconómico):</strong> Modela una jerarquía clásica donde los factores demográficos (edad, sexo) determinan la escolaridad, la cual a su vez influye en el nivel de ingresos y la condición de actividad, condicionando finalmente la tenencia vehicular y las percepciones del entorno.</li>
<li><strong>DAG 2 (Infraestructura):</strong> Establece el tamaño de la localidad poblacional como el nodo raíz principal, asumiendo que el entorno geográfico y la infraestructura urbana rigen directamente la disponibilidad de medios, los tiempos de traslado y el uso de vehículos específicos como el tractor.</li>
<li><strong>DAG 3 (Riesgo y Comportamiento):</strong> Centraliza la topología en los nodos de salida (exposición a delitos y uso del claxon), planteándolos como efectos convergentes que dependen fuertemente del ecosistema automovilístico cerrado y el tiempo de exposición durante los viajes.</li>
</ul>
<p>Para contrastar estas hipótesis teóricas con la estructura latente en los datos, se implementó el algoritmo de aprendizaje automático Hill-Climbing. Este método iterativo heurístico descubre la topología óptima añadiendo y removiendo arcos hasta maximizar el ajuste empírico. Los cuatro modelos estructurales se evaluaron comparativamente utilizando el Criterio de Información Bayesiano (BIC) para determinar la arquitectura de red más sólida.</p>
</section>
<section id="inferencia-bayesiana" class="level3">
<h3 class="anchored" data-anchor-id="inferencia-bayesiana">2.3 Inferencia Bayesiana</h3>
<p>Una vez evaluadas las estructuras, la red bayesiana que demostró el mejor ajuste empírico a los datos (mayor score BIC) fue seleccionada como el modelo definitivo para la fase de aplicación empírica.</p>
<p>La estimación de los parámetros de probabilidad condicional de esta red óptima se realizó mediante un ajuste Bayesiano (<code>method = "bayes"</code>). Para mitigar la inestabilidad en la estimación de nodos con eventos estadísticamente raros en la muestra —específicamente, el uso de tractor en zonas urbanas— se aplicó un factor de suavizado matemático estableciendo un tamaño de muestra imaginario (<code>iss = 10</code>).</p>
<p>La resolución de las interrogantes probabilísticas (queries) se ejecutó sobre este modelo seleccionado mediante técnicas de inferencia aproximada basadas en simulación de Monte Carlo. Se emplearon los métodos de <em>Likelihood Weighting</em> y <em>Logic Sampling</em>, ejecutando 1,000,000 de iteraciones por escenario para garantizar una convergencia precisa de las probabilidades condicionales. Finalmente, para evaluar la relación entre la tenencia vehicular y la incidencia delictiva, se definió la aplicación de una prueba formal de independencia condicional utilizando el estadístico <span class="math inline">G^2</span> de información mutua para cuantificar la significancia estadística formal de la dependencia observada.</p>
</section>
</section>
<section id="aplicación-y-resultados" class="level2">
<h2 class="anchored" data-anchor-id="aplicación-y-resultados">3. Aplicación y Resultados</h2>
<section id="evaluación-y-comparación-de-estructuras-score-bic" class="level3">
<h3 class="anchored" data-anchor-id="evaluación-y-comparación-de-estructuras-score-bic">3.1 Evaluación y Comparación de Estructuras (Score BIC)</h3>
<p>Se evaluó cuantitativamente la bondad de ajuste de los tres DAGs teóricos construidos y del DAG obtenido mediante el algoritmo de aprendizaje estructural <em>Hill-Climbing</em>. La métrica de comparación fue la puntuación BIC (<em>Bayesian Information Criterion</em>), la cual penaliza la complejidad del modelo (número de parámetros) en función del tamaño de la muestra.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 22%">
<col style="width: 22%">
<col style="width: 27%">
<col style="width: 27%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Modelo / Estructura</th>
<th style="text-align: left;">Enfoque Teórico / Algorítmico</th>
<th style="text-align: center;">Score BIC</th>
<th style="text-align: center;">Ranking</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>DAG 1</strong></td>
<td style="text-align: left;">Modelo Socioeconómico Base</td>
<td style="text-align: center;">-9647.92</td>
<td style="text-align: center;">4</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>DAG 3</strong></td>
<td style="text-align: left;">Enfoque de Riesgo y Victimización</td>
<td style="text-align: center;">-9255.19</td>
<td style="text-align: center;">3</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>DAG 2</strong></td>
<td style="text-align: left;">Enfoque de Infraestructura y Geografía</td>
<td style="text-align: center;">-9119.83</td>
<td style="text-align: center;">2</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Hill-Climbing (DAG HC)</strong></td>
<td style="text-align: left;">Aprendizaje Estructural Automatizado</td>
<td style="text-align: center;"><strong>-8653.48</strong></td>
<td style="text-align: center;"><strong>1</strong></td>
</tr>
</tbody>
</table>
<p>El algoritmo <em>Hill-Climbing</em> logró una mejora sustancial en la puntuación BIC (superando por <span class="math inline">+466.35</span> puntos al segundo mejor modelo teórico, DAG 2). Esta superioridad matemática demuestra que las interdependencias empíricas latentes en los microdatos difieren de las suposiciones puramente teóricas, capturando conexiones no intuitivas entre el tamaño de localidad, el ingreso familiar y la preferencia modal.</p>
<section id="representación-gráfica-de-los-grafos-dags" class="level4">
<h4 class="anchored" data-anchor-id="representación-gráfica-de-los-grafos-dags">Representación Gráfica de los Grafos (DAGs)</h4>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="article/dag1_teorico.png" class="img-fluid figure-img" style="width:70.0%"></p>
<figcaption>DAG 1: Modelo Socioeconómico</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="article/dag2_infraestructura.png" class="img-fluid figure-img" style="width:70.0%"></p>
<figcaption>DAG 2: Modelo de Infraestructura</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="article/dag3_riesgo.png" class="img-fluid figure-img" style="width:70.0%"></p>
<figcaption>DAG 3: Modelo de Riesgo</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="article/dag_hc.png" class="img-fluid figure-img" style="width:70.0%"></p>
<figcaption>DAG Aprendido por Hill-Climbing</figcaption>
</figure>
</div>
</section>
</section>
<section id="inferencia-probabilística-y-respuesta-a-las-queries-asignadas" class="level3">
<h3 class="anchored" data-anchor-id="inferencia-probabilística-y-respuesta-a-las-queries-asignadas">3.2 Inferencia Probabilística y Respuesta a las Queries Asignadas</h3>
<p>A partir de la Red Bayesiana ajustada con suavizado Bayesiano (<span class="math inline">\text{iss} = 10</span>), se ejecutaron los algoritmos de muestreo estocástico (<em>Likelihood Weighting</em> y <em>Logic Sampling</em>) para responder formalmente a las cuatro interrogantes de investigación.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 30%">
<col style="width: 30%">
<col style="width: 38%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Query / Escenario</th>
<th style="text-align: left;">Condición / Evidencia Dada</th>
<th style="text-align: center;">Probabilidad Estimada</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Q1: Tractor (Rural)</strong></td>
<td style="text-align: left;"><span class="math inline">P(\text{usa\_tractor} = \text{"Sí"} \mid \text{Tam\_loc\_bin} = \text{"Menos de 15,000 hab."})</span></td>
<td style="text-align: center;"><strong>3.55%</strong> (<span class="math inline">0.035515</span>)</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Q1: Tractor (Urbano)</strong></td>
<td style="text-align: left;"><span class="math inline">P(\text{usa\_tractor} = \text{"Sí"} \mid \text{Tam\_loc\_bin} = \text{"15,000 hab. o más"})</span></td>
<td style="text-align: center;"><strong>0.87%</strong> (<span class="math inline">0.008705</span>)</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Q2: Claxon (Hombres)</strong></td>
<td style="text-align: left;"><span class="math inline">P(\text{p15\_3} \in \text{\{"Siempre", "Casi siempre"\}} \mid \text{sexo} = \text{"Hombre"}, \text{p6} = \text{"Sí"})</span></td>
<td style="text-align: center;"><strong>27.58%</strong> (<span class="math inline">0.275802</span>)</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Q2: Claxon (Mujeres)</strong></td>
<td style="text-align: left;"><span class="math inline">P(\text{p15\_3} \in \text{\{"Siempre", "Casi siempre"\}} \mid \text{sexo} = \text{"Mujer"}, \text{p6} = \text{"Sí"})</span></td>
<td style="text-align: center;"><strong>35.47%</strong> (<span class="math inline">0.354700</span>)</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Q3: Victimización (Con Auto)</strong></td>
<td style="text-align: left;"><span class="math inline">P(\text{victima\_delito} = \text{"Sí"} \mid \text{p6} = \text{"Sí"})</span></td>
<td style="text-align: center;"><strong>17.91%</strong> (<span class="math inline">0.179101</span>)</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Q3: Victimización (Sin Auto)</strong></td>
<td style="text-align: left;"><span class="math inline">P(\text{victima\_delito} = \text{"Sí"} \mid \text{p6} = \text{"No"})</span></td>
<td style="text-align: center;"><strong>11.78%</strong> (<span class="math inline">0.117808</span>)</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Q4: Público (Bajo Ingreso &amp; Trayecto Largo)</strong></td>
<td style="text-align: left;"><span class="math inline">P(\text{medio\_principal} = \text{"Público masivo"} \mid \text{ing\_fam} \in \text{\{"&lt;1 SM", "1-2 SM"\}}, \text{dura1\_cat} = \text{"Largo (&gt;40 min)"})</span></td>
<td style="text-align: center;"><strong>61.35%</strong> (<span class="math inline">0.613507</span>)</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Q4: Auto (Alto Ingreso &amp; Trayecto Corto)</strong></td>
<td style="text-align: left;"><span class="math inline">P(\text{medio\_principal} = \text{"Automóvil particular"} \mid \text{ing\_fam} \geq \text{"4-5 SM"}, \text{dura1\_cat} = \text{"Corto (≤20 min)"})</span></td>
<td style="text-align: center;"><strong>21.96%</strong> (<span class="math inline">0.219592</span>)</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="conclusiones" class="level2">
<h2 class="anchored" data-anchor-id="conclusiones">4. Conclusiones</h2>
<p>El modelado mediante Redes Bayesianas ofreció una perspectiva probabilística integral sobre los determinantes del transporte y la movilidad en México. Las principales conclusiones del estudio se sintetizan a continuación:</p>
<ol type="1">
<li><strong>Superioridad del Aprendizaje Estructural:</strong> El algoritmo <em>Hill-Climbing</em> superó consistentemente a las estructuras deductivas predefinidas (obteniendo un score BIC de <span class="math inline">-8653.48</span>). Esto evidencia que los patrones observados en las encuestas de movilidad urbana poseen una complejidad latente que supera las simplificaciones teóricas tradicionales.</li>
<li><strong>Robustez en Eventos Raros:</strong> La implementación de técnicas de estimación Bayesiana con suavizado mediante muestra imaginaria (<span class="math inline">\text{iss} = 10</span>) permitió parametrizar nodos con eventos de muy baja frecuencia (como el uso de maquinaria agrícola en zonas urbanas), impidiendo la aparición de probabilidades nulas erróneas en la inferencia estocástica.</li>
<li><strong>Implicaciones para Políticas Públicas:</strong>
<ul>
<li>La falta de significancia estadística entre la tenencia vehicular y el delito (<span class="math inline">p = 0.1297</span>) indica que la victimización afecta de manera transversal a los usuarios de la red vial, independientemente del modo de transporte personal.</li>
<li>La fuerte concentración de usuarios de escasos recursos en trayectos largos dentro del transporte público (<span class="math inline">61.35\%</span>) subraya la urgente necesidad de articular políticas de ordenamiento territorial y subsidios focalizados para reducir la brecha de inequidad en tiempos de traslado.</li>
</ul></li>
<li><strong>Limitaciones y Líneas Futuras:</strong> La principal limitación del estudio radica en la muestra reducida disponible para combinaciones específicas de variables categóricas de alta dimensión. Investigaciones futuras podrían explorar algoritmos de aprendizaje de estructuras con restricciones (<em>hybrid structure learning</em>) e incorporar datos espaciales georreferenciados para capturar efectos de accesibilidad urbana a nivel de manzana o microzona.</li>
</ol>
</section>
<section id="referencias" class="level2">
<h2 class="anchored" data-anchor-id="referencias">5. Referencias</h2>
<ul>
<li>Instituto de Investigaciones Jurídicas UNAM. (2026). <em>Encuesta Nacional de Movilidad y Transporte (ENMT)</em>. Universidad Nacional Autónoma de México.</li>
<li>Scutari, M. (2010). Learning Bayesian Networks with the bnlearn R Package. <em>Journal of Statistical Software</em>, 35(3), 1-22.</li>
<li>Pearl, J. (2009). <em>Causality: Models, Reasoning, and Inference</em>. Cambridge University Press.</li>
<li>Repositorio del proyecto: [Inserta aquí tu liga de GitHub]</li>
</ul>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>